### ISSUE TITLE
Print screen broken

### ISSUE THREAD

**Issue by nschwertner** [smart-on-fhir/growth-chart-app#23]
When running the app from https://gallery.smarthealthit.org/boston-childrens-hospital/growth-chart and invoking print functionality for parental view in Chrome and Firefox, the page is broken and the `Print Now` button is off center:

![screen shot 2016-10-25 at 23 20 02](https://cloud.githubusercontent.com/assets/752839/19712238/2ba3b854-9b0a-11e6-9ce1-85eaf8d5feb0.png)

**Comment by vlad-ignatov** [comment]
We have had this issue before and it was fixed here https://github.com/smart-on-fhir/growth-chart-app/commit/47e0d02c14387d2df41caad13cbb3dc2d2edb6d9#diff-563d4cd819b33db15768f253b9c252eb

However, for whatever reason it is back. Perhaps something was reinstalled or moved around and now we don't have the correct version online?

**Comment by nschwertner** [comment]
Hmm, it looks like the copy hosted on "apps-dstu2.smarthealthit.org" for the gallery never got updated with that code. I advanced it to the head of the `master` branch, so now it has all the commits through today and the print screen looks much better:

![screen shot 2016-10-26 at 09 13 56](https://cloud.githubusercontent.com/assets/752839/19727307/dbc81d4a-9b5c-11e6-803d-e15c931dc54b.png)

**Comment by nschwertner** [comment]
The `Print Now` button still appears off center. It's not critical in any way, but I wonder if we can fix it to behave like it used to by any chance?

**Comment by vlad-ignatov** [comment]
The print button is now centered.
